animalcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('animals/', views.animals_index, name='index'),
    path('animals/<int:animal_id>/', views.animals_detail, name='detail'),
    path('animals/create/', views.AnimalCreate.as_view(), name='animals_create'),
    path('animals/<int:pk>/update',
         views.AnimalUpdate.as_view(), name='animals_update'),
    path('animals/<int:pk>/delete',
         views.AnimalDelete.as_view(), name='animals_delete'),
    path('animals/<int:animal_id>/add_feeding/',
         views.add_feeding, name='add_feeding'),
    path('toys/', views.ToyList.as_view(), name='toys_index'),
    path('toys/<int:pk>/', views.ToyDetail.as_view(), name='toys_detail'),
    path('toys/create/', views.ToyCreate.as_view(), name='toys_create'),
    path('toys/<int:pk>/update/', views.ToyUpdate.as_view(), name='toys_update'),
    path('toys/<int:pk>/delete/', views.ToyDelete.as_view(), name='toys_delete'),
    path('animals/<int:animal_id>/assoc_toy/<int:toy_id>/',
         views.assoc_toy, name='assoc_toy'),
]

main_app/models.py
from django.db import models
from django.urls import reverse

MEALS = (
    ('B', 'Breakfast'),
    ('L', 'Lunch'),
    ('D', 'Dinner'),
)


class Toy(models.Model):
    name = models.CharField(max_length=50)
    color = models.CharField(max_length=50)

    def get_absolute_url(self):
        return reverse('toys_detail', kwargs={'pk': self.id})


class Animal(models.Model):
    name = models.CharField(max_length=100)
    type = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    age = models.IntegerField()
    toys = models.ManyToManyField(Toy)

    # changes to instance methods do not require re-generation / running of migrations
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('detail', kwargs={'animal_id': self.id})


class Feeding(models.Model):
    date = models.DateField('Feeding Date')
    meal = models.CharField(
        max_length=1,
        choices=MEALS,
        default=MEALS[0][0]
    )

    animal = models.ForeignKey(Animal, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.get_meal_display()} on {self.date}"

    # change the default sort
    class Meta:
        ordering = ['-date']

main_app/forms.py
from django.forms import ModelForm
from .models import Feeding


class FeedingForm(ModelForm):
    class Meta:
        model = Feeding
        fields = ['date', 'meal']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Animal, Toy
from .forms import FeedingForm
# Create your views here.


def home(request):
    return render(request, 'home.html')


def about(request):
    return render(request, 'about.html')


# class Animal:  # Note that parens are optional if not inheriting from another class
#     def __init__(self, name, type, description, age):
#         self.name = name
#         self.type = type
#         self.description = description
#         self.age = age


# animals = [
#     Animal('Rhino', 'Mammal', 'big horns', 40),
#     Animal('Turtle', 'reptile', 'hides in shell', 95),
#     Animal('bass', 'fish', 'eats', 5),
#     Animal('horse', 'mammal', 'runs', 25),
# ]


def animals_index(request):
    animals = Animal.objects.all()
    return render(request, 'animals/index.html', {'animals': animals})


def animals_detail(request, animal_id):
    animal = Animal.objects.get(id=animal_id)
    return render(request, 'animals/detail.html', {'animal': animal})


def animals_detail(request, animal_id):
    animal = Animal.objects.get(id=animal_id)
    feeding_form = FeedingForm()
    toys_animal_doesnt_have = Toy.objects.exclude(
        id__in=animal.toys.all().values_list('id'))
    return render(request, 'animals/detail.html', {
        'animal': animal,
        'feeding_form': feeding_form,
        'toys': toys_animal_doesnt_have,
    })


def add_feeding(request, animal_id):
    form = FeedingForm(request.POST)
    if form.is_valid():
        new_feeding = form.save(commit=False)
        new_feeding.animal_id = animal_id
        new_feeding.save()
    return redirect('detail', animal_id=animal_id)


def assoc_toy(request, animal_id, toy_id):
    Animal.objects.get(id=animal_id).toys.add(toy_id)
    return redirect('detail', animal_id=animal_id)


class AnimalCreate(CreateView):
    model = Animal
    fields = '__all__'
    success_url = '/animals/'


class AnimalUpdate(UpdateView):
    model = Animal
    fields = ['type', 'description', 'age']


class AnimalDelete(DeleteView):
    model = Animal
    success_url = '/animals/'


class ToyCreate(CreateView):
    model = Toy
    fields = ('name', 'color')


class ToyUpdate(UpdateView):
    model = Toy
    fields = ('name', 'color')


class ToyDelete(DeleteView):
    model = Toy
    success_url = '/toys/'


class ToyDetail(DetailView):
    model = Toy
    template_name = 'toys/detail.html'


class ToyList(ListView):
    model = Toy
    template_name = 'toys/index.html'

main_app/templates/about.html
{% extends 'base.html' %}{% block content %}
<h1>About the Animal Collector</h1>
    <hr />
    <p>Hire the Animal Collector!</p>
{% endblock %}

main_app/templates/animals/detail.html
{% extends 'base.html' %}{% block content%}

<h1>Animal Details</h1>

<div class="row">
    <div class="col s6">
<div class="card">
    <div class="card-content">
        <span class="card-title">{{animal.name}}</span>
        <p>Type: {{animal.type}}</p>
        <p>Descirption: {{animal.description}}</p>
        {% if animal.age > 2%}
        <p>Age: {{animal.age}}</p>
        {% else %}
        <p>Age: Baby</p>
        {% endif %}
    </div>
    <div class="card-action">
        <a href="{% url 'animals_update' animal.id%}">Edit</a>
        <a href="{% url 'animals_delete' animal.id%}">Delete</a>
    </div>
</div>
</div>
<div class="col s6">
    <form action="{% url 'add_feeding' animal.id%}" method="post">
        {% csrf_token %} {{ feeding_form.as_p }}
        <input type="submit" class="btn" value="Add Feeding" />
      </form>
    <table class="striped">
        <thead>
            <th>Date</th>
            <th>Meal</th>
        </thead>
        <tbody>
            {% for feeding in animal.feeding_set.all %}
            <tr>
                <td>{{feeding.date}}</td>
                <td>{{feeding.get_meal_display}}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
</div>

<!-- This is all new markup to be added just above the <script> tag -->
    <hr />
    <div class="row">
    
        <div class="col s6">
            <h3>{{ animal.name }}'s Toys</h3>
            {% if animal.toys.count %} {% for toy in animal.toys.all %}
            <div class="card">
                <div class="card-content">
                    <span class="card-title">
                        A <span class="color: {{ toy.color.lower }}-text">
                            {{ toy.color }}</span> {{ toy.name }}
                    </span>
                </div>
            </div>
            {% endfor %} {% else %}
            <h5>No Toys :(</h5>
            {% endif %}
        </div>
    
    
        <!-- Available toys will come after this line -->
        <div class="col s6">
            <h3>Available Toys</h3>
            {% if toys.count %}
            {% for toy in toys.all %}
            <div class="card">
                <div class="card-content">
                    <span class="card-title">
                        A <span class="{{ toy.color }}-text">{{ toy.color }}</span> {{ toy.name }}
                    </span>
                </div>
                <div class="card-action">
                    <form action="{% url 'assoc_toy' animal.id toy.id %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn">Add</button>
                    </form>
                </div>
            </div>
            {% endfor %}
            {% else %}
            <h5>{{animal.name}} Already Has All Toys Available</h5>
            {% endif %}
        </div>
    </div>
    
<script>  
var dateEl = document.getElementById('id_date');
    M.Datepicker.init(dateEl, {
      format: 'yyyy-mm-dd',
      defaultDate: new Date(),
      setDefaultDate: true,
      autoClose: true
    });

    var selectEl = document.getElementById('id_meal');
  M.FormSelect.init(selectEl);
</script>
{% endblock %}

main_app/templates/animals/index.html
{% extends 'base.html' %} {% block content %}

<h1>Animal List</h1>

{% for animal in animals %}
<div class="card">
    <a href="/animals/{{animal.id}}">
  <div class="card-content">
    <span class="card-title">{{ animal.name }}</span>
    <p>Type: {{ animal.type }}</p>
    <p>Description: {{ animal.description }}</p>
    {% if animal.age > 2 %}
    <p>Age: {{ animal.age }}</p>
    {% else %}
    <p>Age: Baby</p>
    {% endif %}
  </div>
  </a>
</div>
{% endfor %} {% endblock %}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Animal Collector</title>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"
    />
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  </head>
  <body>
    <header class="navbar-fixed">
      <nav>
        <div class="nav-wrapper">
          <ul>
            <li>
              <a href="/" class="left brand-logo">  AnimalCollector</a>
            </li>
          </ul>
          <ul class="right">
            <li><a href="{% url 'about' %}">About</a></li>
            <li><a href="{% url 'index' %}">View All My Animals</a></li>
            <li><a href="{% url 'animals_create' %}">Add an Animal</a></li>
            <li><a href="{% url 'toys_create' %}">Add a Toy</a></li>
            <li><a href="{% url 'toys_index' %}">View All My Toys</a></li>
          </ul>
        </div>
      </nav>
    </header>
    <main class="container">{% block content %} {% endblock %}</main>
    <footer class="page-footer">
      <div class="right">
        All Rights Reserved, &copy; 2022 Animal Collector  
      </div>
    </footer>
  </body>
</html>

main_app/templates/home.html
    {% extends 'base.html' %}{% block content %}
    <h1>Welcome to the Animal Collector Home Page!</h1>
    <hr />
    <p>Select your favorite animal from the catalog of different animals!</p>
    {% endblock %}

main_app/templates/main_app/animal_confirm_delete.html
{% extends 'base.html' %} {% block content %}
<h1>Delete Animal</h1>

<h4>
    Are you sure you want to delete
    <span class="teal-text">{{object.name}}</span>?
</h4>

<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes- Delete!" class="btn" />
    <a href="{% url 'detail' animal.id%}">Cancel</a>
</form>
{% endblock %}

main_app/templates/main_app/animal_form.html
{% extends 'base.html' %}{% block content %}
{% if object %}
<h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
<h1>Add Animal</h1>
{% endif %}
<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn" />
</form>
{% endblock %}

main_app/templates/main_app/toy_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

<h1>Delete Toy</h1>

<h4>
    Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?
</h4>

<form action="" method="post">
    {% csrf_token %}
    <input class="btn red" type="submit" value="Yes - Delete">
    <a class="btn blue" href="{% url 'detail' object.id %}">Cancel</a>
</form>

{% endblock %}

main_app/templates/main_app/toy_form.html
{% extends 'base.html' %}

{% block content %}

{% if object %}
    <h1>Update {{ object.name }}</h1>
{% else %}
    <h1>Add Toy</h1>
{% endif %}

<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input class="btn blue" type="submit" value="{% if object %} Update Toy {% else %} Add Toy {% endif %}">
</form>

{% endblock %}

main_app/templates/toys/detail.html
{% extends 'base.html' %}

{% block content %}

<h1>Toy Details</h1>


<div class="card">
    <a href="{% url 'toys_detail' toy.id %}">
        <div class="card-content">
            <span class="card-title">A <span class="{{ toy.color.lower }}-text">{{ toy.color }}</span> {{ toy.name }}</span>
        </div>
        <div class="card-action">
            <a href="{% url 'toys_update' toy.id %}">Edit</a>
            <a href="{% url 'toys_delete' toy.id %}">Delete</a>
        </div>
    </a>
</div>

{% endblock %}

main_app/templates/toys/index.html
{% extends 'base.html' %}

{% block content %}

<h1>Toys List</h1>
{% for toy in object_list %}
<div class="card">
    <a href="{% url 'toys_detail' toy.id %}">
        <div class="card-content">
            <span class="card-title">A <span class="{{ toy.color }}-text"></span> {{ toy.name }}</span>
        </div>
    </a>
</div>
{% endfor %}


{% endblock %}